SELECT EMPLOYEE_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID FROM SALARIES)
OR NAME IS NULL
UNION
SELECT EMPLOYEE_ID
FROM SALARIES
WHERE EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID FROM EMPLOYEES)